### ISSUE TITLE
Download link error

### ISSUE THREAD

**Issue by zhuxinguang33** [scene-verse/SceneVerse#18]
Thanks for such a wonderful work. But the dataset download link [https://docs.google.com/forms/d/1x8cCAkn86d6MyyY5PMvvS_qRrH7dV8_RKHeBX9sE3KU](url) is wrong. It shows the file has been deleted!
Could please fix it?

**Comment by Buzz-Beater** [comment]
Hi, as I just tried with the link on the website and in this repo, it seems working for me, can you try refreshing your browser cache and checking the link again? Previously, we had a data migration because of the new google drive education workspace regulations, so it's most likely an old link was there. The form link is https://docs.google.com/forms/d/e/1FAIpQLSdWN-aGts3VZZcQF6Q0iGY_Kl6bnz_q0w8sDy_y7wgsz5e24g/viewform, but I would recommend you still check the link you got by refershing in case you miss any updates.

**Comment by zhuxinguang33** [comment]
I tried many times but still failed. So I‘ll just use the form link. Thanks a lot.

**Comment by Buzz-Beater** [comment]
Sure, just let us know if you face any other download issues, currently it does not seem to be a common problem but it's worth noticing.
