### ISSUE TITLE
Dataset Link

### ISSUE THREAD

**Issue by strongwolf** [scene-verse/SceneVerse#20]
Hello, I submitted the form for downloading the dataset several days ago but have not received the link yet.

**Comment by Buzz-Beater** [comment]
Hi, the link is provided on the last page of the submission form (right after you submit the form there is still a page saying thanks and saying that "you can view your scores"). You will not receive a separate email for the download link. The page looks like this 

![image](https://github.com/user-attachments/assets/7b667341-d49b-4b1b-8d32-bb5b942dc746)

And sorry for not providing the link in this comment since we still want each downloader of SceneVerse to be aware of all the licenses, so let me know if there is still any issue with data download.
