### ISSUE TITLE
Questions on the split files

### ISSUE THREAD

**Issue by chrockey** [scene-verse/SceneVerse#5]
Hi,

Some datasets like 3RScan, ARKitScenes, HM3D, and MultiScan consist of multiple split files, each denoting different subsets. Specifically, they have three types of split files: `{train/val}_split_before_filter.txt`, `{train/val}_split_non_overlap.txt`, and `{train/val}_split.txt`. Could you clarify the distinctions among these split files?

Furthermore, in ProcThor, there are `{train/val}_split_all.txt` as well as `{train/val}_split.txt`. What is the difference between these files?

Thanks!

**Comment by yixchen** [comment]
Hi,

Sorry for the confusion. The `{train/val}_split_non_overlap.txt` is meant for the per-dataset experiment in the early stage of the project. Later we merge them to create a larger training set, i.e., `train_split_before_filter.txt`. In our final experiments, we use `{train/val}_split.txt` for all the datasets by filtering out 'problematic' scenes, e.g., too large, too small, or multi-floor. In short words,

1. Use `{train/val}_split.txt` to reproduce the experiments in the paper. The `val.txt` for `MultiScan` is the `SceneVerse-val`. There is no `val.txt` for `ARKitScenes, HM3D, 3RScan` because we are not validating on them.
2. The `train_split_before_filter.txt` = `train_split_non_overlap.txt` + `train_split_non_overlap.txt`.
3. `train.txt` + `filter_out scenes` = `train_split_before_filter.txt`

We may clear out the unnecessary files if people find them confusing in a later version.

Best,

**Comment by chrockey** [comment]
Thank you for the reply! It resolved most of my confusion except `train_split_all.txt`. What is the difference between `train_split_all.txt` and `train_split.txt` in ProcThor?

**Comment by yixchen** [comment]
Yes, you are right. And I have updated the previous comment accordingly.

**Comment by chrockey** [comment]
I see. Thank you very much for kind reply :)
